services:
  tinker-agent:
    build:
      context: .
      dockerfile: Dockerfile
    models:
      qwen2_5_latest:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN_LATEST
      gemma3_latest:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_GEMMA3_LATEST
      qwen2_5_1_5b_f16:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN2_5_1_5B_F16
      qwen2_5_3b_f16:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN2_5_3B_F16
      qwen3_0_6b_q4_k_m:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN3_0_6B_Q4_K_M
    


models:
  qwen2_5_latest:
    model: ai/qwen2.5:latest
  gemma3_latest:
    model: ai/gemma3:latest
  qwen2_5_1_5b_f16:
    model: ai/qwen2.5:1.5B-F16
  qwen2_5_3b_f16:
    model: ai/qwen2.5:3B-F16
  qwen3_0_6b_q4_k_m:
    model: ai/qwen3:0.6B-Q4_K_M

