services:
  tinker-agent:
    build:
      context: .
      dockerfile: Dockerfile
    models:
      qwen2_5_latest:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN_LATEST
      gemma3_latest:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_GEMMA3_LATEST
      qwen3_0_6b_q4_k_m:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN3_0_6B_Q4_K_M
      qwen3_latest:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL_QWEN3_LATEST

    
models:
  qwen2_5_latest:
    model: ai/qwen2.5:latest
  gemma3_latest:
    model: ai/gemma3:latest
  qwen3_0_6b_q4_k_m:
    model: ai/qwen3:0.6B-Q4_K_M
  qwen3_latest:
    model: ai/qwen3:latest

